/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import transaksi.transaksi;
/**
 *
 * @author YUSUF KRISNA . N
 */
class adminlog{
    String usernameadmin = "yusuf",passwordadmin = "yusuf";
}
class userlog{
    String userp = "pelanggan", passwp = "pelanggan";
}
public class loginpembeli extends javax.swing.JFrame {
private transaksi trans;
adminlog adm = new adminlog();
userlog user = new userlog();
    /**
     * Creates new form login
     */
    public loginpembeli() throws SQLException {
        initComponents();
        this.trans = new transaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        idreg1 = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JToggleButton();
        pembeli = new javax.swing.JLabel();
        awal2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(907, 40, 100, 32);

        idreg1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        idreg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idreg1ActionPerformed(evt);
            }
        });
        jPanel1.add(idreg1);
        idreg1.setBounds(560, 290, 460, 80);
        jPanel1.add(password);
        password.setBounds(560, 450, 460, 90);

        login.setBackground(new java.awt.Color(51, 51, 51));
        login.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(680, 580, 240, 90);

        pembeli.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pembeli.setForeground(new java.awt.Color(255, 255, 255));
        pembeli.setText("kembali ke pembeli");
        pembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pembeliMousePressed(evt);
            }
        });
        jPanel1.add(pembeli);
        pembeli.setBounds(830, 730, 150, 19);

        awal2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        awal2.setForeground(new java.awt.Color(255, 255, 255));
        awal2.setText("kembali ke awal");
        awal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                awal2MousePressed(evt);
            }
        });
        jPanel1.add(awal2);
        awal2.setBounds(630, 730, 120, 19);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Untitled-1 copy.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1024, 774);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idreg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idreg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idreg1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        try {
        if(idreg1.getText().equals(adm.usernameadmin) && password.getText().equals(adm.passwordadmin)){
            new admin().show();
            new loginpembeli().setVisible(false);
        }
        }catch(SQLException err){
            System.out.println(err);
        }
        setVisible(false);
    }//GEN-LAST:event_loginActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new pembeli().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void pembeliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembeliMousePressed
        // TODO add your handling code here:
        new pembeli().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_pembeliMousePressed

    private void awal2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_awal2MousePressed
        // TODO add your handling code here:
        new awal().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_awal2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new loginpembeli().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(loginpembeli.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel awal2;
    private javax.swing.JButton back;
    private javax.swing.JTextField idreg1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel pembeli;
    // End of variables declaration//GEN-END:variables
}
